# Generated by Django 5.2.8 on 2025-12-01 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Apertura')),
                ('start_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Inicial (Base)')),
                ('end_amount_system', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Saldo Calculado por Sistema')),
                ('end_amount_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinero Real en Caja (Conteo)')),
                ('difference', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Diferencia (Sobrante/Faltante)')),
                ('is_closed', models.BooleanField(default=False, verbose_name='¿Caja Cerrada?')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
            ],
            options={
                'verbose_name': 'Caja Diaria',
                'verbose_name_plural': 'Historial de Cajas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Ingreso 🟢'), ('OUT', 'Egreso 🔴')], max_length=3, verbose_name='Tipo de Movimiento')),
                ('category', models.CharField(choices=[('SALES', 'Venta de Comida'), ('PURCHASE', 'Compra de Insumos'), ('SERVICE', 'Pago de Servicios (Luz/Agua)'), ('SALARY', 'Sueldos'), ('OTHER', 'Otros Movimientos')], max_length=20, verbose_name='Categoría')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción / Razón')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (Bs)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Hora Exacta')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.cashregister', verbose_name='Pertenece a la Caja')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Movimientos de Dinero',
                'ordering': ['-timestamp'],
            },
        ),
    ]
