# Generated by Django 5.2.8 on 2025-12-01 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_dish', models.BooleanField(default=False, verbose_name='¿Es Plato?')),
                ('base_unit', models.CharField(choices=[('KG', 'Kilogramos (Sólidos)'), ('L', 'Litros (Líquidos)'), ('U', 'Unidades (Huevos/Platos)')], default='KG', max_length=2, verbose_name='Unidad Base')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10, verbose_name='Stock Actual')),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre (Ej: Arroba)')),
                ('base_unit', models.CharField(choices=[('KG', 'Kilogramos (Sólidos)'), ('L', 'Litros (Líquidos)'), ('U', 'Unidades (Huevos/Platos)')], max_length=2, verbose_name='Tipo Base')),
                ('conversion_factor', models.DecimalField(decimal_places=3, default=1, help_text='Cuántos Kilos/Litros tiene esta unidad. Ej: Arroba = 11.5', max_digits=10)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity_produced', models.PositiveIntegerField(verbose_name='Platos Obtenidos')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('unit_cost_real', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('dish', models.ForeignKey(limit_choices_to={'is_dish': True}, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
            },
        ),
        migrations.CreateModel(
            name='ProductionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost_calculated', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('ingredient', models.ForeignKey(limit_choices_to={'is_dish': False}, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_used', to='inventory.production')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='Compra Insumos', max_length=200)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.cashregister', verbose_name='Caja que paga')),
            ],
            options={
                'verbose_name': 'Nota de Compra',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
                ('origin_purchase', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchase')),
            ],
            options={
                'verbose_name': 'Lote de Inventario',
                'ordering': ['entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dish', models.ForeignKey(limit_choices_to={'is_dish': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.product')),
                ('ingredient', models.ForeignKey(limit_choices_to={'is_dish': False}, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('customer_name', models.CharField(default='Cliente Casual', max_length=100)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.cashregister')),
            ],
            options={
                'verbose_name': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('dish', models.ForeignKey(limit_choices_to={'is_dish': True}, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bought', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total')),
                ('product', models.ForeignKey(limit_choices_to={'is_dish': False}, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase')),
                ('unit_bought', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
            },
        ),
    ]
