# Generated by Django 5.2.8 on 2025-12-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['entry_date']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='batch',
            name='origin_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchase'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('KG', 'Kg / Litros (Base)'), ('U', 'Unidades (Platos)')], default='KG', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity_produced',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.cashregister'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity_bought',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_bought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='base_unit',
            field=models.CharField(choices=[('KG', 'Kg / Litros (Base)'), ('U', 'Unidades (Platos)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
